package com.infomaniak.calendar.secured

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import dev.zacsweers.metro.Inject
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

private const val DAV_CREDENTIAL_KEY = "davCredentialKey"
private const val ANDROID_KEYSTORE = "AndroidKeyStore"
private const val CIPHER_TRANSFORMATION = "AES/GCM/NoPadding"
private const val GCM_TAG_LENGTH = 128
private const val AES_KEY_SIZE = 256

/**
 * Provides AES/GCM encryption and decryption backed by the Android Keystore.
 *
 * The 256-bit secret key is generated on first use and stored securely under the alias
 * [DAV_CREDENTIAL_KEY] in the Android Keystore. It is never exported outside the Keystore,
 * protecting it against extraction even on rooted devices.
 *
 * All cryptographic operations run on [Dispatchers.IO].
 */
class KeystoreCipher @Inject constructor() {

    private val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    /**
     * Active AES secret key retrieved from the Android Keystore.
     * If no key exists yet under [DAV_CREDENTIAL_KEY], a new one is generated.
     * Access is synchronized to prevent concurrent key creation.
     */
    private val secretKey: SecretKey
        @Synchronized get() = (keyStore.getEntry(DAV_CREDENTIAL_KEY, null) as? KeyStore.SecretKeyEntry)?.secretKey
            ?: generateNewKey()

    /**
     * Generates and stores a new 256-bit AES key in the Android Keystore.
     *
     * The key is configured for GCM encryption and decryption with no padding.
     * It is bound to the Keystore and cannot be exported.
     *
     * @return The newly generated [SecretKey].
     */
    private fun generateNewKey(): SecretKey {
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
            init(
                KeyGenParameterSpec.Builder(DAV_CREDENTIAL_KEY, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(AES_KEY_SIZE)
                    .build(),
            )
        }.generateKey()
    }

    /**
     * Encrypts a plain-text string using AES/GCM with the Keystore-backed key.
     *
     * A random IV is generated by the cipher on each call, ensuring that encrypting
     * the same value twice produces distinct ciphertexts.
     *
     * @param value Plain-text string to encrypt (UTF-8 encoded).
     * @return An [EncryptionResult] containing the IV and the ciphertext, both Base64-encoded.
     */
    suspend fun encrypt(value: String): EncryptionResult = withContext(Dispatchers.IO) {
        val cipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val initializationVector = cipher.iv.encodeToBase64()
        val encryptedData = cipher.doFinal(value.toByteArray(Charsets.UTF_8)).encodeToBase64()
        EncryptionResult(initializationVector, encryptedData)
    }

    /**
     * Decrypts AES/GCM ciphertext using the Keystore-backed key.
     *
     * The IV must exactly match the one produced during encryption; any mismatch
     * will cause decryption to fail with an exception.
     *
     * @param encryptedValue Ciphertext to decrypt, Base64-encoded.
     * @param initializationVector IV used during encryption, Base64-encoded.
     * @return The decrypted plain-text string (UTF-8).
     * @throws javax.crypto.AEADBadTagException If the data has been tampered with or the IV is incorrect.
     */
    suspend fun decrypt(encryptedValue: String, initializationVector: String): String {
        return withContext(Dispatchers.IO) {
            val cipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
            val spec = GCMParameterSpec(GCM_TAG_LENGTH, initializationVector.decodeFromBase64())
            cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)
            String(cipher.doFinal(encryptedValue.decodeFromBase64()), Charsets.UTF_8)
        }
    }

    private fun ByteArray.encodeToBase64(): String = Base64.encodeToString(this, Base64.NO_WRAP)
    private fun String.decodeFromBase64(): ByteArray = Base64.decode(this, Base64.NO_WRAP)
}
